WebAPIApp/Controllers/UserEmailController.cs
using System;
using System.Net.Mail;
using System.Net;
using System.Web.Mvc;
using System.IO;
using SHPOT_BLL;
using SHPOT_ViewModel;
using System.Configuration;
using System.Net.Mime;

namespace WebAPIApp.Controllers
{
    /// <summary>
    /// Controller For Sending Emails
    /// </summary>
    public class UserEmailController : Controller
    {
        #region [ Constructor and Private Members ]
        User_BLL _userBLL;

        public UserEmailController()
        {
            _userBLL = new User_BLL();
        }

        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region [ Forgot Password ]
        /// <summary>
        /// Forgot Password
        /// </summary>
        /// <param name="_userVM"></param>
        /// <returns></returns>
        // POST web/useremail/ForgotPassword
        [HttpPost]
        public void ForgotPassword(UserVM _userVM)
        {
            HttpContext.Response.ContentType = "application/json; charset=utf-8";
            try
            {
                //Check If User Exists

                _userVM = _userBLL.ForgotPassword(_userVM);

                if (_userVM != null)
                {
                    //Fetching Email Body Text from EmailTemplate File.  
                    string FilePath = Server.MapPath(@"~\EmailTemplates") + @"\ForgotPassword.html";
                    StreamReader str = new StreamReader(FilePath);
                    string MailText = str.ReadToEnd();
                    str.Close();

                    //Repalce EmailTemplate Parameters                        
                    MailText = MailText.Replace("[#SHPOT]", "SHPOT");
                    MailText = MailText.Replace("[#FirstName]", _userVM.FirstName);
                    MailText = MailText.Replace("[#FullName]", _userVM.FirstName + " " + _userVM.LastName);
                    MailText = MailText.Replace("[#ActionURL]", Common.APIURL + "/Web/UserEmail/ResetUserPassword/" + _userVM.ResetToken);
                    MailText = MailText.Replace("[#SupportURL]", Common.APIURL + "/Web/UserEmail/AddSupportQuery/");

                    String _fromEmail = Common.SMTPUserName;
                    String _fromName = "SHPOT Admin";
                    String _toEmail = _userVM.Email;
                    String _toName = _userVM.FirstName;

                    SendEmailNotifications(_fromEmail, _fromName, _toEmail, _toName, MailText, "Password Reset URL - SHPOT");

                    HttpContext.Response.Write("{\"status\": \"Success\",");
                    HttpContext.Response.Write("\"Message\": \"A link has been sent to your email.\"}");
                }
                else
                {
                    HttpContext.Response.Write("{\"status\": \"Failed\",");
                    HttpContext.Response.Write("\"Message\": \"User does not exists.\"}");
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.Write("{\"status\": \"Failed\", ");
                HttpContext.Response.Write("\"Message\": \"" + ex.Message + "\"}");
            }
        }
        #endregion

        #region [ Reset User Password ]
        /// <summary>
        /// Reset User Password
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult ResetUserPassword(String value)
        {
            if (TempData["SuccessMessage"] != null)
            {
                ViewBag.ShowForm = false;
                ViewBag.SuccessMessage = TempData["SuccessMessage"].ToString();
                TempData["SuccessMessage"] = null;
                return View();
            }

            UserVM _userVM = _userBLL.CheckResetPwdValidity(value);
            ViewBag.UnSuccessMessage = null;
            ViewBag.SuccessMessage = null;

            if (_userVM != null)
            {
                ViewBag.InvalidURL = null;
                ViewBag.ShowForm = true;
                UserVM model = new UserVM() { ResetToken = value };
                return View(model);
            }
            else
            {
                ViewBag.ShowForm = false;
                ViewBag.UnSuccessMessage = "Sorry, Invalid URL. It has been expired now. Please try again for new password.";
                return View();
            }
        }

        /// <summary>
        /// Reset Password POST Mode
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ResetUserPassword(UserVM model)
        {
            ViewBag.UnSuccessMessage = null;
            ViewBag.SuccessMessage = null;
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.UnSuccessMessage = "Please enter password.";
                    return View("AddSupportQuery", model);
                }
                else
                {
                    if (!string.IsNullOrEmpty(model.Password))
                    {
                        model.Password = Common.EncryptedPassword(model.Password);
                        UserVM _userVM = _userBLL.ResetPassword(model);
                        TempData["SuccessMessage"] = "Password has been updated successfuly.";
                        return RedirectToAction("ResetUserPassword");
                    }
                    else
                        return View("ResetUserPassword", model);
                }
            }
            catch (Exception ex)
            {
                ViewBag.UnSuccessMessage = "Please goto forgot password process again. Some error has occurred. Error is: " + ex.Message;
            }
            return View("ResetUserPassword");
        }
        #endregion

        #region [ Add Support Query ]
        /// <summary>
        /// Add Support Query
        /// </summary>
        /// <returns></returns>
        public ActionResult AddSupportQuery()
        {
            return View();
        }

        /// <summary>
        /// Add Support Query
        /// </summary>
        /// <param name="_Email"></param>
        /// <param name="_Query"></param>
        /// <returns></returns>
        // POST web/useremail/addsupportquery
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddSupportQuery(SupportQueryVM _supportQuery)
        {
            try
            {
                ViewBag.UnSuccessMessage = null;
                ViewBag.SuccessMessage = null;

                if (!ModelState.IsValid)
                {
                    ViewBag.UnSuccessMessage = "Please enter your Email Address/Query.";
                    return View("AddSupportQuery");
                }
                else
                {
                    _supportQuery.IPAddress = Request.UserHostAddress;

                    if (_supportQuery.EmailAddress != string.Empty && _supportQuery.Query != string.Empty)
                    {
                        _supportQuery = new Business_BLL().AddSupportQuery(_supportQuery);

                        if (_supportQuery != null)
                        {
                            ViewBag.SuccessMessage = "Your query has been submitted successfully. Support person will contact you shortly to help you with this.";

                            //Send Email to Admin
                            //Fetching Email Body Text from EmailTemplate File.  
                            string FilePath = Server.MapPath(@"~\EmailTemplates") + @"\SupportQuery.html";
                            StreamReader str = new StreamReader(FilePath);
                            string MailText = str.ReadToEnd();
                            str.Close();

                            //Repalce EmailTemplate Parameters                        
                            MailText = MailText.Replace("[#SHPOT]", "SHPOT");
                            MailText = MailText.Replace("[#FULLNAME]", _supportQuery.FullName);
                            MailText = MailText.Replace("[#IPADDRESS]", _supportQuery.IPAddress);
                            MailText = MailText.Replace("[#QUERYDATE]", _supportQuery.QueryDateTime.ToString());
                            MailText = MailText.Replace("[#EMAILID]", _supportQuery.EmailAddress);
                            MailText = MailText.Replace("[#QUERY]", _supportQuery.Query);

                            String _fromEmail = _supportQuery.EmailAddress;
                            String _fromName = _supportQuery.FullName;
                            String _toEmail = Common.SMTPUserName;
                            String _toName = "SHPOT Admin";
                            SendEmailNotifications(_supportQuery.EmailAddress, _supportQuery.FullName, _toEmail, _toName, MailText, "Support Query By: " + _supportQuery.FullName);
                        }
                        else
                            ViewBag.UnSuccessMessage = "Please submit your query again.";
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.UnSuccessMessage = "Please submit your query again. Some error has occurred. Error is: " + ex.Message;
            }
            return View("AddSupportQuery");
        }
        #endregion

        #region [ Send Email Notifications ]
        /// <summary>
        /// Send Email Notifications
        /// </summary>
        /// <param name="_fromEmail"></param>
        /// <param name="_fromName"></param>
        /// <param name="_toEmail"></param>

WebAPIApp/Views/UserEmail/AddSupportQuery.cshtml
@model SHPOT_ViewModel.SupportQueryVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "SHPOT - Support";
}

<h3>Support Query</h3>
<hr />
<span class="text-success">@ViewBag.SuccessMessage</span>

<span class="text-danger">@ViewBag.UnSuccessMessage</span>

@using (Html.BeginForm("AddSupportQuery", "UserEmail", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    Html.EnableClientValidation(true);

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <span class="control-label col-md-2">Full Name</span>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FullName, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">Email Address</span>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmailAddress, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">Query / Suggestion</span>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Query, 4, 2, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebAPIApp/Views/UserEmail/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}

<h3>Index</h3>

WebAPIApp/Views/UserEmail/ResetUserPassword.cshtml
@model SHPOT_ViewModel.UserVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reset Password";
}

<h3>Reset Password</h3>
<hr />
<span class="text-success">@ViewBag.SuccessMessage</span>

<span class="text-danger">@ViewBag.UnSuccessMessage</span>

@if (ViewBag.ShowForm)
{
    using (Html.BeginForm("ResetUserPassword", "UserEmail", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        Html.EnableClientValidation(true);

        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ResetToken)

            <div class="form-group">
                <span class="control-label col-md-2">New Password</span>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <span class="control-label col-md-2">Confirm Password</span>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}